#!/bin/bash

set -e

wget https://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.gz  -O - | tar xz
cd binutils-2.31.1
./configure --prefix=/opt/devtools-8.2/
make -j4
make install
cd ..

wget https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.gz -O - | tar xz
mkdir -p gcc
cd gcc
ORGLDFLAGS=$LDFLAGS
unset LDFLAGS
../gcc-8.2.0/configure --prefix=/opt/devtools-8.2 --with-gmp=/opt/devtools-8.2 --with-mpfr=/opt/devtools-8.2 --with-mpc=/opt/devtools-8.2 --enable-languages=c,c++ --disable-multilib --with-stage1-ldflags="-L/opt/devtools-8.2/lib64 -Wl,-rpath,/opt/devtools-8.2/lib64 -L/opt/devtools-7.2/lib64 -Wl,-rpath,/opt/devtools-7.2/lib64" --with-boot-ldflags="-L/opt/devtools-8.2/lib64 -Wl,-rpath,/opt/devtools-8.2/lib64"
LD_LIBRARY_PATH="/opt/devtools-7.2/lib64" make -j4
make install
