#!/bin/bash

set -e

wget --no-check-certificate https://nixos.org/releases/patchelf/patchelf-0.10/patchelf-0.10.tar.gz -O - | tar xz
cd patchelf-0.10
CXXFLAGS="$CXXFLAGS -static-libstdc++" LDFLAGS="$LDFLAGS -static-libstdc++" ./configure --prefix=/opt/devtools-9.2
make -j4
make install
cd -

wget http://mirror.internode.on.net/pub/gnu/gmp/gmp-6.1.2.tar.bz2 -O - | tar xj
cd gmp-6.1.2
./configure --prefix=/opt/devtools-9.2 --libdir=/opt/devtools-9.2/lib64
make -j4
make install
cd ..

wget http://www.mpfr.org/mpfr-current/mpfr-4.0.2.tar.bz2 -O - | tar xj
cd mpfr-4.0.2
./configure --prefix=/opt/devtools-9.2 --libdir=/opt/devtools-9.2/lib64
make -j4
make install
cd ..

wget http://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz -O - | tar xz
cd mpc-1.1.0
./configure --prefix=/opt/devtools-9.2 --libdir=/opt/devtools-9.2/lib64
make -j4
make install
cd ..
