#!/usr/bin/env bash
set -e

cd src

ABI=64

if [ $(uname -m) = "i686" ]; then
    ABI=32
fi

wget http://ftp.gmplib.org/gmp/gmp-5.1.3.tar.bz2
tar xf gmp-5.1.3.tar.bz2
cd gmp-5.1.3
ABI=$ABI ./configure --prefix=/opt/devtools
make -j4
make install
cd ..

wget http://www.mpfr.org/mpfr-current/mpfr-3.1.2.tar.bz2
tar xf mpfr-3.1.2.tar.bz2
cd mpfr-3.1.2
./configure --prefix=/opt/devtools
make -j4
make install
cd ..

wget http://www.multiprecision.org/mpc/download/mpc-1.0.1.tar.gz
tar xf mpc-1.0.1.tar.gz 
cd mpc-1.0.1
./configure --prefix=/opt/devtools
make -j4
make install
cd ..
