#!/usr/bin/env bash


GCC=$(/opt/devtools-4.9/bin/gcc --version | head -n 1 | awk '{ print $3 }')
BINUTILS=$(/opt/devtools-4.9/bin/ld --version | head -n 1 | awk '{ print $5 }')

tar cf - /opt/devtools-4.9 | bzip2 --best - > gcc-$GCC-multilib-binutils-$BINUTILS-$(uname -m).tar.bz2 

